### PR TITLE
fix(event-recurrence): skipping first not aligned date when BYDAY is set

### LINKED ISSUE #1062: Weekly RRULE with BYDAY doesn't include first matching date if DTSTART doesn't align
I ran into a possible issue when creating a recurring event using the following RRULE:
`RRULE:FREQ=WEEKLY;INTERVAL=1;UNTIL=20251231T235959;BYDAY=FR`

I set the start date (DTSTART) to 2025-05-17, which is a saturday (one day after the last Friday).

Given that the rule specifies a weekly recurrence on fridays, I expected the first occurrence to be on 2025-05-23. However, this date is being skipped.

For comparison:

[rrule node library](https://www.npmjs.com/package/rrule) 
Image

Google Calendar (API created)
Image

Schedule-X displays it like this:
Image

### PR DESCRIPTION
**Pull request by jcbertoli**
## Checklist

Please put "X" in the below checkboxes that apply:

- [X] If committing a change of production code, I have tested it in different browsers (Chrome, Firefox, Safari). 
- [X] If committing a new feature, I have first submitted an issue (Please note: you are free to open PRs for non-issued features, but opening an issue increases your chance of a successful PR). 
- [X] If committing a new feature, I have also written the appropriate tests for it. 
- [X] I have tried to build the feature in a way, that it does not cause any breaking changes for others (unless 
  agreed upon in an issue). 

**Premium**
- [ ] I'm a Schedule-X premium user

## This PR solves the following problem. 

This PR should fix #1062.

## How to test this PR. 
The event
```
{
      id: 123,
      title: 'Weekly event',
      start: '2025-05-17 14:00',
      end: '2025-05-17 15:00',
      rrule: 'RRULE:FREQ=WEEKLY;INTERVAL=1;UNTIL=20251231T235959;BYDAY=FR',
}
```
will now be displayed correctly
image

### CODE REVIEW

File: packages/event-recurrence/src/util/stateless/create-recurrences-for-event.ts [hunk 1]
```diff
@@ -28,18 +28,19 @@ export const createRecurrencesForEvent = (
...
-    .getRecurrences()
-    .slice(1) // skip the first occurrence because this is the original event
-    .map((recurrence) => {
-      const eventCopy: AugmentedEvent = deepCloneEvent(calendarEvent, $app)
-      eventCopy.start = recurrence.start
-      eventCopy.end = recurrence.end
-      eventCopy.isCopy = true
-      return eventCopy
-    })
+  if (recurrenceSet[0].start == calendarEvent.start) {
```
Comment (tomosterlund) [inline packages/event-recurrence/src/util/stateless/create-recurrences-for-event.ts:33]: Uh nice! Wouldn't have expected the fix to be so simple. I was already drawing up some big changes in my mind after reading your issue, but this seems both simpler and better :) 

any reason for not doing a strict check, or can we change to `if (recurrenceSet[0].start == calendarEvent.start) {`?

**Comment by jcbertoli** [comment]
Should we do the same check for background events?

**Comment by tomosterlund** [comment]
> Should we do the same check for background events?

thanks for thinking of it, I did not!

That would make sense, yes

**Review by tomosterlund — APPROVED** [review]
